apiVersion: appstudio.redhat.com/v1alpha1
kind: BuildPipelineSelector
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: build-pipeline-selector
  namespace: build-service
spec:
  selectors:
  - name: FBC
    pipelineRef:
      params:
      - name: name
        value: fbc-builder
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9
      - name: kind
        value: pipeline
      resolver: bundles
    when:
      language: fbc
  - name: Docker build
    pipelineRef:
      params:
      - name: name
        value: docker-build
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9
      - name: kind
        value: pipeline
      resolver: bundles
    when:
      dockerfile: true
  - name: Java
    pipelineRef:
      params:
      - name: name
        value: java-builder
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-java-builder:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9
      - name: kind
        value: pipeline
      resolver: bundles
    when:
      language: java
  - name: NodeJS
    pipelineRef:
      params:
      - name: name
        value: nodejs-builder
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-nodejs-builder:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9
      - name: kind
        value: pipeline
      resolver: bundles
    when:
      language: nodejs,node
