name: Sanity Test

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      
      - name: Show version infromation
        run: |
          kubectl version
          kind version

      - name: List namespaces
        run: |
          kubectl get namespace
